name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull lucasgojeda/portfoliov4:latest

      - name: Delete old Docker container
        run: sudo docker rm -f portfoliov4-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8000:8000 --name portfoliov4-container lucasgojeda/portfoliov4
