name: CI Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io

      - name: Build the Docker image
        run: docker build -t portfoliov4 .

      - name: Tag docker image
        run: docker tag portfoliov4 lucasgojeda/portfoliov4:latest

      - name: Push to DockerHub
        run: docker push lucasgojeda/portfoliov4:latest
